site_name: Funmorning Transit

site_url: https://funmoring46.github.io/FunmorningTransit

theme:
  name: material
  language: en
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: yellow

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
  icon:
    annotation: material/information

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption
  - abbr
  - pymdownx.snippets
  - tables

plugins:
  - search
  - glightbox
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Funmorning Transit"
          theme:
            font:
              text: Rubik
        - locale: zh
          name: 简体中文
          build: true
          site_name: "funmorning公共交通"
          theme:
            font:
              text: LXGWNeoXiHei
        - locale: ja
          name: 日本語
          build: true
          site_name: "funmorning公共交通"
          theme:
            font:
              text: Murecho

nav:
  - index.md
  - howtoplay.md
  - aboutthetransp.md
  - stations.md
  - planning.md
  - Stations/车站/駅:
      - stations/mountains.md
      - stations/home.md
      - stations/view.md
      - stations/forest.md
      - stations/village.md
      - stations/lakesideforest.md
      - stations/crumble_mountain.md
      - stations/thompson_road.md
      - stations/spawn.md
      - stations/airport_terminal_one.md
      - stations/shuliu.md
      - stations/kuangzhen.md
      - stations/norton_forest.md
      - stations/kiyama.md
      - stations/beach.md
      - stations/oaklands.md
        - Bus Stations/公共汽车站/バス停:
          - stations/bus/mountains.md
  - Lines/线/線:
      - lines/lineone.md

extra_css:
  - stylesheets/extra.css